/* auto-generated compile shim */
export type AnyZodRawShape = any
export type ForkSessionOptions = any
export type ForkSessionResult = any
export type GetSessionInfoOptions = any
export type GetSessionMessagesOptions = any
export type InferShape = any
export type InternalOptions = any
export type InternalQuery = any
export type ListSessionsOptions = any
export type McpSdkServerConfigWithInstance = any
export type Options = any
export type Query = any
export type SDKSession = any
export type SDKSessionOptions = any
export type SdkMcpToolDefinition = any
export type SessionMessage = any
export type SessionMutationOptions = any
