/* auto-generated compile shim */
export type AgentToolProgress = any
export type BashProgress = any
export type MCPProgress = any
export type PowerShellProgress = any
export type REPLToolProgress = any
export type SdkWorkflowProgress = any
export type ShellProgress = any
export type SkillToolProgress = any
export type TaskOutputProgress = any
export type ToolProgressData = any
export type WebSearchProgress = any
