/* auto-generated compile shim */
export type BillingType = any
export type OAuthProfileResponse = any
export type OAuthTokenExchangeResponse = any
export type OAuthTokens = any
export type RateLimitTier = any
export type ReferralCampaign = any
export type ReferralEligibilityResponse = any
export type ReferralRedemptionsResponse = any
export type ReferrerRewardInfo = any
export type SubscriptionType = any
export type UserRolesResponse = any
